### ISSUE TITLE
mit_license_badge.svg is a 404

### ISSUE THREAD

**Issue by cben** [shaypal5/catlolzer#1]
No such file in this repo, apparently.
looking at shields.io, I see they have https://img.shields.io/pypi/l/catlolzer.svg which should check PyPI license metadata, but it's empty.  No idea why, https://pypi.org/project/catlolzer/ seems to have license fields.
Or you can just use shields.io custom-text badge e.g. https://img.shields.io/badge/license-MIT-green.svg

**Comment by shaypal5** [comment]
I prefer using a file in the repo (like I do in my other repos) since shields.io became super unstable over the last few months.

It was just a file I forgot to copy from my skift repo. Fixed now.
